name: Rust

on:
  push:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --all --check
      - name: Build
        run: |
          for package in $(ls -d lab*); do
            (cd $package && cargo build)
          done
      - name: Clippy
        run: |
          for package in $(ls -d lab*); do
            (cd $package && cargo clippy)
          done
